server:
  port: 8005

spring:
  application:
    name: MessageSerive # 多个同功能的服务使用应用名来注册,这个应用名你可以在eureka 中看到,它变成了服务名

# eureka配置:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka # 指定eureka 服务端交互地址
  instance:
    instance-id: MessageSerive8005 # 当前服务实例名称,如果不指定,是主机名:服务名称:服务端口
    prefer-ip-address: true # 是否使用IP地址作为当前服务的标识,有些是会使用主机号,你可以尝试注释看看效果
#    由于拉取服务和是否把自己注册到eureka的都是默认true的,所以不需要配置
