server:
  port: 80


feign:
  hystrix:
    enabled: true # 用来开启fegin中的hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false # 由于它不是一个服务提供者,不注册到eureka